//! Symbolic item sampling: fact graphs with a known answer and known
//! distractor verdicts, drawn from [`crate::vocab`] pools.
//!
//! Every sampler constructs the *structure first* (a dependency chain,
//! a health board, a bring-up order), then derives the facts, the gold
//! answer, and a candidate ballot whose non-gold slots are **known
//! wrong by construction** — symptoms carry a failing cause below them,
//! the standalone failure has no dependents, the runner-up is one
//! report behind. [`crate::verify`] then proves the rendered item
//! against the engine's own solver (choice families) or re-derives the
//! level from the extracted facts (the score family), so a sampler bug
//! or a rendering that the extraction grammar mis-reads fails loudly
//! instead of poisoning the corpus with a mislabeled slot.
//!
//! # Minimal pairs (§9.7 B4)
//!
//! [`corrupt_to_pair`] turns a root-cause item into a two-sided
//! contrastive pair: flip the root's health fact, and the gold moves
//! to the node above — same question, same ballot, one fact different,
//! both sides independently proved. The twin is emitted only when the
//! base carries the exact shape the corruption needs; anything else
//! emits the base alone.
//!
//! # Operator interference
//!
//! The engine's [`RelationalSolver`](opencodifier_engine::relational::RelationalSolver)
//! runs three operators over whatever
//! facts are present and requires every firing operator to agree. A
//! sampler that ignores the operators it is not targeting can
//! accidentally make a second operator fire and disagree, which turns
//! the item into a delegation. The interference rules baked in here:
//!
//! * root-cause items may contain **zero or ≥2** single healthy
//!   statements — exactly one would let `healthiest` prove the healthy
//!   peer against the gold (a 1-vs-0 strict win). Two tie and it
//!   abstains.
//! * first-restored side chains must attach **under** an existing
//!   waiter — a detached `x1 after x0` would make `x0` a second
//!   wait-for-nothing starter and break uniqueness.
//! * healthiest boards carry no dependency or ordering facts, so the
//!   other two operators have nothing to fire on.
//! * score boards carry no dependency or ordering facts for the same
//!   reason; their verdict is pure report arithmetic.

use opencodifier_engine::facts::{Health, RelationalFact};

use crate::rng::Rng;
use crate::vocab::{self, DOMAINS, DOWN_WORDS, Domain};

/// Which symbolic sampler produced an item. Four choice families (two
/// per targeted proof shape, so the corpus carries generator structural
/// diversity by construction rather than by after-the-fact mix) plus
/// the score family that manufactures the non-constant score rows the
/// merged corpus lacks (§9.7 B2).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Family {
    /// Dependency chain, failure set, one provable root cause.
    RootCauseChain,
    /// Root cause *and* bring-up order facts that independently prove
    /// the same node — two operators agreeing on one answer.
    RootCauseAgreeing,
    /// Health-report board, one strictly-ahead entity.
    HealthiestBoard,
    /// Bring-up ordering chain, one wait-for-nothing starter.
    FirstRestoredChain,
    /// Health-report board scored on the fixed 4-level rubric — the
    /// score-family manufacture (§9.7 B2). Verified by extraction +
    /// rubric re-derivation, not the choice solver (there is no
    /// candidate ballot; the "ballot" is the fixed level scale).
    ScoreBoard,
}

/// The choice families, in generation rotation order. Score items are
/// generated by explicit selection (`--families sb`), not rotation, so
/// the relational slice's composition stays stable across runs.
pub const FAMILIES: &[Family] = &[
    Family::RootCauseChain,
    Family::RootCauseAgreeing,
    Family::HealthiestBoard,
    Family::FirstRestoredChain,
];

/// Every family, in `--families` code order.
pub const GENERATION_FAMILIES: &[Family] = &[
    Family::RootCauseChain,
    Family::RootCauseAgreeing,
    Family::HealthiestBoard,
    Family::FirstRestoredChain,
    Family::ScoreBoard,
];

impl Family {
    /// The `source` tag written into corpus records.
    #[must_use]
    pub fn source_tag(self) -> &'static str {
        match self {
            Family::RootCauseChain => "itemgen/root-cause-chain",
            Family::RootCauseAgreeing => "itemgen/root-cause-agreeing",
            Family::HealthiestBoard => "itemgen/healthiest-board",
            Family::FirstRestoredChain => "itemgen/first-restored-chain",
            Family::ScoreBoard => "itemgen/score-board",
        }
    }

    /// The single-letter code accepted by the `--families` flag.
    #[must_use]
    pub fn code(self) -> &'static str {
        match self {
            Family::RootCauseChain => "rcc",
            Family::RootCauseAgreeing => "rca",
            Family::HealthiestBoard => "hb",
            Family::FirstRestoredChain => "frc",
            Family::ScoreBoard => "sb",
        }
    }

    /// Parses a `--families` entry.
    #[must_use]
    pub fn from_code(code: &str) -> Option<Self> {
        GENERATION_FAMILIES.iter().copied().find(|family| family.code() == code)
    }

    /// The question phrasing pool this family draws from.
    fn phrasings(self) -> &'static [&'static str] {
        match self {
            Family::RootCauseChain | Family::RootCauseAgreeing => vocab::ROOT_CAUSE_QUESTIONS,
            Family::HealthiestBoard => vocab::HEALTHIEST_QUESTIONS,
            Family::FirstRestoredChain => vocab::FIRST_RESTORED_QUESTIONS,
            Family::ScoreBoard => vocab::SCORE_QUESTIONS,
        }
    }
}

/// Why a non-gold candidate is wrong. The kind is what makes a negative
/// *hard*: every near-miss shares surface features with the gold (it is
/// failing, it is on the chain, it has reports) while being provably
/// excluded by the proof structure.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DistractorKind {
    /// Failing because the gold below it fails — a symptom, not a cause.
    Symptom,
    /// Failing with nothing depending on it — repairing it restores
    /// nothing else.
    StandaloneFailure,
    /// Fully healthy — repairing a healthy entity restores nothing.
    HealthyPeer,
    /// On the ballot with no stated facts at all.
    Unrelated,
    /// One healthy report behind the winner.
    RunnerUp,
    /// Plenty of reports, none of them healthy.
    DegradedHeavy,
    /// Absent from the board entirely.
    ZeroReport,
    /// Gates something but also waits — mid-chain, provably not first.
    Waiter,
    /// Pure waiter — the end of the bring-up order.
    LastInOrder,
}

/// All distractor kinds, for census reporting.
pub const DISTRACTOR_KINDS: &[DistractorKind] = &[
    DistractorKind::Symptom,
    DistractorKind::StandaloneFailure,
    DistractorKind::HealthyPeer,
    DistractorKind::Unrelated,
    DistractorKind::RunnerUp,
    DistractorKind::DegradedHeavy,
    DistractorKind::ZeroReport,
    DistractorKind::Waiter,
    DistractorKind::LastInOrder,
];

/// One ballot slot: a candidate the corpus supervises with a " no"
/// verdict, and the structural reason it is wrong.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Distractor {
    /// The entity name.
    pub name: String,
    /// Why it is provably not the answer.
    pub kind: DistractorKind,
}

/// One sampled item before rendering: the fact set, the gold answer,
/// the near-miss ballot, and the provenance tags.
#[derive(Debug, Clone)]
pub struct Sampled {
    /// The facts the state text will state (render order is decided
    /// later; this order is never observable).
    pub facts: Vec<RelationalFact>,
    /// The candidate the solver must prove.
    pub gold: String,
    /// The non-gold ballot, each with its known-wrong reason.
    pub distractors: Vec<Distractor>,
    /// Which sampler built this.
    pub family: Family,
    /// The entity-naming domain.
    pub domain: &'static Domain,
    /// Index into the family's phrasing pool.
    pub phrasing: usize,
}

/// Draws unique entity names from a domain pool.
fn take_names(rng: &mut Rng, domain: &Domain, count: usize) -> Vec<&'static str> {
    let mut pool: Vec<&'static str> = domain.names.to_vec();
    rng.shuffle(&mut pool);
    pool.into_iter().take(count).collect()
}

/// Samples one item from `family`. Panics only on sampler-internal
/// invariants (an empty pool is a static vocabulary bug, checked in
/// [`crate::vocab`] tests); verification of the *output* is
/// [`crate::verify`]'s job, not this function's.
#[must_use]
pub fn sample(family: Family, rng: &mut Rng) -> Sampled {
    let domain = rng.pick(DOMAINS);
    let phrasing = rng.below(family.phrasings().len());
    let mut sampled = match family {
        Family::RootCauseChain => root_cause(rng, domain, false),
        Family::RootCauseAgreeing => root_cause(rng, domain, true),
        Family::HealthiestBoard => healthiest(rng, domain),
        Family::FirstRestoredChain => first_restored(rng, domain),
        Family::ScoreBoard => score_board(rng, domain),
    };
    sampled.family = family;
    sampled.domain = domain;
    sampled.phrasing = phrasing;
    sampled
}

/// The score rubric over report counts `(healthy, degraded, down)` —
/// the integer form of the level scale stated in
/// [`crate::vocab::SCORE_QUESTIONS`] and [`crate::vocab::SCORE_LEVELS`].
/// Disjoint and exhaustive for any total ≥ 1; pure integer arithmetic,
/// so the same counts always map to the same level.
///
/// * level 0 (critical): `2·down > total` — downs are the majority
/// * level 1 (poor): downs present, not a majority, and
///   `2·(degraded + down) ≥ total` — failures reach half
/// * level 2 (mixed): failures present but healthy leads, or nothing
///   down with degraded leading
/// * level 3 (healthy): nothing down and healthy ≥ degraded
#[must_use]
pub fn health_level(healthy: usize, degraded: usize, down: usize) -> usize {
    let total = healthy + degraded + down;
    if 2 * down > total {
        0
    } else if down > 0 && 2 * (degraded + down) >= total {
        1
    } else if down > 0 || degraded > healthy {
        2
    } else {
        3
    }
}

/// Counts report statuses across Health/HealthList facts — the tally
/// the score rubric consumes. Used on BOTH sides of score-item
/// verification: the record gold is derived from the constructed fact
/// set through [`health_level`], and the verifier re-derives it from
/// the extracted set through this same function, so the two cannot
/// diverge on what counts as a report.
#[must_use]
pub fn count_statuses(facts: &[RelationalFact]) -> (usize, usize, usize) {
    fn bump(counts: &mut (usize, usize, usize), status: Health) {
        match status {
            Health::Healthy => counts.0 += 1,
            Health::Degraded => counts.1 += 1,
            Health::Down => counts.2 += 1,
        }
    }
    let mut counts = (0usize, 0usize, 0usize);
    for fact in facts {
        match fact {
            RelationalFact::Health { status, .. } => bump(&mut counts, *status),
            RelationalFact::HealthList { statuses, .. } => {
                for status in statuses {
                    bump(&mut counts, *status);
                }
            }
            RelationalFact::DependsOn { .. } | RelationalFact::RestoresAfter { .. } => {}
        }
    }
    counts
}

/// Draws report counts `(healthy, degraded, down)` realizing `level`
/// exactly, with a total in the entity-feasible range. Used by the
/// score sampler so the level census spreads across all four bands by
/// construction instead of by luck.
fn counts_for_level(level: usize, total: usize, rng: &mut Rng) -> (usize, usize, usize) {
    let (h, d, x) = match level {
        0 => {
            // 2x > t: x strictly above half.
            let min_x = total / 2 + 1;
            let x = min_x + rng.below(total - min_x + 1);
            let rest = total - x;
            let d = rng.below(rest + 1);
            (rest - d, d, x)
        }
        1 => {
            // x ≥ 1, 2x ≤ t, 2(d + x) ≥ t, d ≤ t − x.
            let max_x = total / 2;
            let x = 1 + rng.below(max_x);
            let min_d = total.div_ceil(2) - x;
            let d = min_d + rng.below(total - x - min_d + 1);
            (total - x - d, d, x)
        }
        2 => {
            // Two realizing shapes: a failure present but healthy-led,
            // or nothing down with degraded leading.
            if total >= 3 && rng.percent(50) {
                // nothing down, degraded > healthy
                let min_d = total / 2 + 1;
                let d = min_d + rng.below(total - min_d + 1);
                (total - d, d, 0)
            } else {
                // x ≥ 1 with 2(d + x) < t; needs t ≥ 4.
                let x = 1 + rng.below((total - 1) / 2);
                let max_d = (total - 1) / 2 - x;
                let d = rng.below(max_d + 1);
                (total - x - d, d, x)
            }
        }
        _ => {
            // Nothing down, healthy ≥ degraded.
            let h = total.div_ceil(2) + rng.below(total - total.div_ceil(2) + 1);
            let d = total - h;
            (h, d, 0)
        }
    };
    (h, d, x)
}

/// Score-board sampler: a health board whose gold level is derived from
/// the report counts through [`health_level`]. The level is drawn
/// first (uniform), then counts are constructed to realize it — the
/// non-degenerate score distribution is a sampler invariant, not a
/// hope. The gold is stored as the level index string, which is the
/// label the prep's score path supervises.
fn score_board(rng: &mut Rng, domain: &'static Domain) -> Sampled {
    let entity_count = 2 + rng.below(4); // 2..=5
    let entities = take_names(rng, domain, entity_count);
    let per_entity = entities.len();
    // Statuses per entity 1..=3 → total in [n, 3n]; level 2's
    // failure-present branch needs a total ≥ 4.
    let mut total = per_entity + rng.below(2 * per_entity + 1);
    let level = rng.below(4);
    if level == 2 && total < 4 {
        total = 4;
    }
    let (h, d, x) = counts_for_level(level, total, rng);

    // Deal the statuses across entities, one each first, then the
    // remainder capped at two extras per entity (total ≤ 3n holds by
    // construction).
    let mut statuses: Vec<Health> = std::iter::repeat_n(Health::Healthy, h)
        .chain(std::iter::repeat_n(Health::Degraded, d))
        .chain(std::iter::repeat_n(Health::Down, x))
        .collect();
    rng.shuffle(&mut statuses);
    let mut per_entity_statuses: Vec<Vec<Health>> =
        entities.iter().map(|_| Vec::with_capacity(3)).collect();
    for (index, slot) in per_entity_statuses.iter_mut().enumerate() {
        slot.push(statuses[index]);
    }
    let mut next = per_entity;
    let mut pass = 0;
    while next < statuses.len() {
        for slot in &mut per_entity_statuses {
            if next >= statuses.len() {
                break;
            }
            if pass < 2 {
                slot.push(statuses[next]);
                next += 1;
            }
        }
        pass += 1;
    }

    let mut facts = Vec::new();
    for (name, slot) in entities.iter().zip(&per_entity_statuses) {
        if slot.len() == 1 {
            facts.push(RelationalFact::Health { entity: (*name).to_owned(), status: slot[0] });
        } else {
            facts.push(RelationalFact::HealthList {
                entity: (*name).to_owned(),
                statuses: slot.clone(),
            });
        }
    }

    Sampled {
        facts,
        gold: level.to_string(),
        distractors: Vec::new(), // the fixed level scale is the ballot
        family: Family::ScoreBoard,
        domain,
        phrasing: 0,
    }
}

/// Builds the minimal-pair twin of a root-cause item: flip the root's
/// health fact from down to healthy — a ONE-FACT corruption — and the
/// gold legitimately moves to the node directly above (it is now the
/// failing node with no failing dependency). Both sides are verified
/// independently by [`crate::verify`], so the pair is provable on both
/// flanks; the question text is unchanged between the twins.
///
/// Returns `None` when the base does not carry the shape the corruption
/// needs — a down root with a down direct dependent, AND another single
/// healthy statement already present (after the flip the old gold
/// becomes one; a LONE healthy statement would let the `healthiest`
/// operator strictly win and vote against the twin's gold, while two
/// tie and it abstains). The caller emits the base alone rather than
/// forcing a bad pair.
#[must_use]
pub fn corrupt_to_pair(base: &Sampled) -> Option<Sampled> {
    if base.family != Family::RootCauseChain {
        return None;
    }
    let other_healthy_single = base.facts.iter().any(|fact| {
        matches!(
            fact,
            RelationalFact::Health { entity, status: Health::Healthy } if *entity != base.gold
        )
    });
    if !other_healthy_single {
        return None;
    }
    // The direct dependent of the root: the chain edge root → child.
    let child = base.facts.iter().find_map(|fact| match fact {
        RelationalFact::DependsOn { dependent, dependency } if *dependency == base.gold => {
            Some(dependent.clone())
        }
        _ => None,
    })?;
    // The child must already be failing (it is a symptom by sampler
    // construction; refusing to synthesize new failures keeps the twin
    // a one-fact edit of the base).
    let child_down =
        base.facts.iter().any(|fact| matches!(fact, RelationalFact::Health { entity, status: Health::Down } if *entity == child));
    if !child_down {
        return None;
    }
    let mut twin = base.clone();
    twin.facts = base
        .facts
        .iter()
        .map(|fact| match fact {
            RelationalFact::Health { entity, status: Health::Down } if *entity == base.gold => {
                RelationalFact::Health { entity: base.gold.clone(), status: Health::Healthy }
            }
            other => other.clone(),
        })
        .collect();
    twin.gold = child;
    // The new gold sat on the base ballot as the root's symptom — it
    // must leave the distractor list or the twin's ballot carries the
    // same id twice.
    twin.distractors.retain(|d| d.name != twin.gold);
    // Recompute the twin's census kinds: the old gold is now a healthy
    // peer, the old symptoms of the old gold are symptoms of the new
    // gold when they hang below it, everything else keeps its reason.
    let old_gold = base.gold.clone();
    for d in &mut twin.distractors {
        if d.name == old_gold {
            d.kind = DistractorKind::HealthyPeer;
        } else if matches!(d.kind, DistractorKind::Symptom)
            && !twin.facts.iter().any(|f| {
                matches!(
                    f, RelationalFact::DependsOn { dependent, dependency }
                    if *dependent == d.name && *dependency == twin.gold
                )
            })
        {
            d.kind = DistractorKind::StandaloneFailure;
        }
    }
    // The old gold leaves the gold slot but STAYS on the ballot — now
    // a healthy peer, the strongest near-miss the pair carries. This
    // keeps the two ballots equal as sets, which is the pair contract.
    twin.distractors.push(Distractor { name: old_gold, kind: DistractorKind::HealthyPeer });
    Some(twin)
}

/// Root cause over a dependency chain; `with_order` adds bring-up
/// facts so a second operator independently proves the same node.
fn root_cause(rng: &mut Rng, domain: &'static Domain, with_order: bool) -> Sampled {
    // Name budget: chain L + standalone + unrelated, plus two for the
    // healthy pair when the pool affords it. Pools are 6-10 names, so
    // small pools drop the pair, never the chain.
    let pair_fits = domain.names.len() >= 7;
    let want_pair = pair_fits && rng.percent(55);
    let headroom = if want_pair { 4 } else { 2 };
    let max_chain = (domain.names.len() - headroom).min(5);
    let chain_len = 3 + rng.below(max_chain - 2);
    let names = take_names(rng, domain, chain_len + headroom);

    let (chain, rest) = names.split_at(chain_len);
    let gold = chain[0].to_owned();
    // Symptoms: the two nodes directly above the root always fail —
    // they are the hardest near-misses (failing AND on the chain) and
    // two of them plus the standalone failure guarantee the ≥3
    // near-miss floor regardless of chain length or the healthy-pair
    // draw. Members beyond those fail with 60% each.
    let mut symptoms: Vec<String> = chain[1..3].iter().map(|name| (*name).to_owned()).collect();
    for name in chain.get(3..).unwrap_or(&[]) {
        if rng.percent(60) {
            symptoms.push((*name).to_owned());
        }
    }
    let standalone = rest[0].to_owned();
    let unrelated = rest[1].to_owned();

    let mut facts = Vec::new();
    for pair in chain.windows(2) {
        facts.push(RelationalFact::DependsOn {
            dependent: pair[1].to_owned(),
            dependency: pair[0].to_owned(),
        });
        if with_order {
            facts.push(RelationalFact::RestoresAfter {
                later: pair[1].to_owned(),
                earlier: pair[0].to_owned(),
            });
        }
    }
    facts.push(RelationalFact::Health { entity: gold.clone(), status: Health::Down });
    for symptom in &symptoms {
        facts.push(RelationalFact::Health { entity: symptom.clone(), status: Health::Down });
    }
    facts.push(RelationalFact::Health { entity: standalone.clone(), status: Health::Down });
    // The healthy pair: two entities with one healthy report each — a
    // tie, so `healthiest` abstains and cannot vote against the gold.
    // One of them is on the ballot (a healthy peer is a plausible-looking
    // wrong answer), the other is off-ballot report noise.
    let mut distractors: Vec<Distractor> = Vec::new();
    for symptom in symptoms.iter().take(2) {
        distractors.push(Distractor { name: symptom.clone(), kind: DistractorKind::Symptom });
    }
    distractors
        .push(Distractor { name: standalone.clone(), kind: DistractorKind::StandaloneFailure });
    if want_pair {
        let healthy_ballot = rest[2].to_owned();
        let healthy_noise = rest[3].to_owned();
        facts.push(RelationalFact::Health {
            entity: healthy_ballot.clone(),
            status: Health::Healthy,
        });
        facts.push(RelationalFact::Health {
            entity: healthy_noise.clone(),
            status: Health::Healthy,
        });
        distractors.push(Distractor { name: healthy_ballot, kind: DistractorKind::HealthyPeer });
    }
    distractors.push(Distractor { name: unrelated, kind: DistractorKind::Unrelated });
    // The ballot must always carry at least five slots (≥3 near-misses
    // per TRAINING.md §9.7 B3); a short chain with one symptom tops up
    // from the remaining chain members, which carry no stated fact.
    let mut ballot_size = distractors.len() + 1;
    for name in &chain[1..] {
        if ballot_size >= 5 {
            break;
        }
        let already_on = distractors.iter().any(|d| d.name == *name);
        if !already_on {
            distractors
                .push(Distractor { name: (*name).to_owned(), kind: DistractorKind::Unrelated });
            ballot_size += 1;
        }
    }

    Sampled { facts, gold, distractors, family: Family::RootCauseChain, domain, phrasing: 0 }
}

/// Healthiest board: strictly-ahead winner, runner-up one report back,
/// a report-heavy but unhealthy entity, and a silent entity.
fn healthiest(rng: &mut Rng, domain: &'static Domain) -> Sampled {
    let names = take_names(rng, domain, 5);
    let best_count = 2 + rng.below(3); // 2..=4 healthy reports
    let counts = [best_count, best_count - 1, best_count.saturating_sub(2), 0, 0];
    // winner, runner-up, third, degraded-heavy, zero-report
    let (winner, runner, third, heavy, silent) = (names[0], names[1], names[2], names[3], names[4]);

    let mut facts = Vec::new();
    let mut distractors = Vec::new();

    for (name, count) in names.iter().take(3).zip(counts.iter()) {
        let count = *count;
        if count == 0 {
            continue;
        }
        // Surface form: group report, or a single statement when the
        // count is 1 — both aggregate to the same number (the grammar
        // accepts both; the solver counts them uniformly).
        if count == 1 && rng.percent(50) {
            facts.push(RelationalFact::Health {
                entity: (*name).to_owned(),
                status: Health::Healthy,
            });
        } else {
            let mut statuses = vec![Health::Healthy; count];
            let filler = rng.below(3); // 0..=2 filler statuses
            for _ in 0..filler {
                statuses.push(if rng.percent(60) { Health::Degraded } else { Health::Down });
            }
            rng.shuffle(&mut statuses);
            facts.push(RelationalFact::HealthList { entity: (*name).to_owned(), statuses });
        }
    }
    // Degraded-heavy: two or three reports, none healthy.
    let heavy_statuses: Vec<Health> = (0..2 + rng.below(2))
        .map(|_| if rng.percent(70) { Health::Degraded } else { Health::Down })
        .collect();
    facts.push(RelationalFact::HealthList { entity: heavy.to_owned(), statuses: heavy_statuses });
    // Silent entity: no facts at all — a named candidate the board
    // says nothing about.

    distractors.push(Distractor { name: runner.to_owned(), kind: DistractorKind::RunnerUp });
    if counts[2] > 0 {
        distractors.push(Distractor { name: third.to_owned(), kind: DistractorKind::RunnerUp });
    } else {
        distractors.push(Distractor { name: third.to_owned(), kind: DistractorKind::ZeroReport });
    }
    distractors.push(Distractor { name: heavy.to_owned(), kind: DistractorKind::DegradedHeavy });
    distractors.push(Distractor { name: silent.to_owned(), kind: DistractorKind::ZeroReport });

    Sampled {
        facts,
        gold: winner.to_owned(),
        distractors,
        family: Family::HealthiestBoard,
        domain,
        phrasing: 0,
    }
}

/// First restored: a bring-up chain with exactly one wait-for-nothing
/// starter, plus a side chain attached *under* the chain's tail (never
/// detached — a detached starter would be a second first).
fn first_restored(rng: &mut Rng, domain: &'static Domain) -> Sampled {
    let max_chain = (domain.names.len() - 2).min(5);
    let chain_len = 3 + rng.below(max_chain - 2);
    let names = take_names(rng, domain, chain_len + 1);
    let (chain, extra) = names.split_at(chain_len);
    let side_waiter = extra[0];

    let mut facts = Vec::new();
    for pair in chain.windows(2) {
        facts.push(RelationalFact::RestoresAfter {
            later: pair[1].to_owned(),
            earlier: pair[0].to_owned(),
        });
    }
    // Side chain under the tail: side_waiter waits on the chain's last
    // node. It is a pure waiter (never first) and it adds a second
    // gate to the tail node, which is itself already a waiter — the
    // unique wait-for-nothing starter stays the chain head.
    facts.push(RelationalFact::RestoresAfter {
        later: side_waiter.to_owned(),
        earlier: chain[chain_len - 1].to_owned(),
    });

    let mut distractors = vec![
        Distractor { name: chain[1].to_owned(), kind: DistractorKind::Waiter },
        Distractor { name: chain[chain_len - 1].to_owned(), kind: DistractorKind::LastInOrder },
        Distractor { name: side_waiter.to_owned(), kind: DistractorKind::Waiter },
    ];
    if chain_len >= 4 {
        distractors.push(Distractor { name: chain[2].to_owned(), kind: DistractorKind::Waiter });
    }
    // Top the ballot up to the five-slot floor from names the order
    // never mentions — a named candidate the bring-up facts say
    // nothing about is provably not the starter.
    let mut ballot_size = 1 + distractors.len();
    for name in domain.names {
        if ballot_size >= 5 {
            break;
        }
        let in_chain = chain.contains(name);
        let already_on = distractors.iter().any(|d| d.name == *name);
        if !in_chain && !already_on {
            distractors
                .push(Distractor { name: (*name).to_owned(), kind: DistractorKind::Unrelated });
            ballot_size += 1;
        }
    }

    Sampled {
        facts,
        gold: chain[0].to_owned(),
        distractors,
        family: Family::FirstRestoredChain,
        domain,
        phrasing: 0,
    }
}

/// The question text for a sampled item: phrasing pool entry with the
/// domain noun substituted.
#[must_use]
pub fn question_text(sampled: &Sampled) -> String {
    sampled.family.phrasings()[sampled.phrasing].replace("{noun}", sampled.domain.noun)
}

/// The status word used to state `Down` for `name` — one of the
/// synonyms, drawn per fact so the surface varies while the fact does
/// not.
#[must_use]
pub fn down_word(rng: &mut Rng) -> &'static str {
    // Turbofish: under rustc 1.90 inference picks T = str (unsized) for a
    // `&[&str]` argument; naming T = &str is accepted by every toolchain.
    rng.pick::<&str>(DOWN_WORDS)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

    use super::*;

    #[test]
    fn root_cause_chain_has_the_gold_and_a_near_miss_ballot() {
        let mut rng = Rng::new(3);
        for _ in 0..200 {
            let sampled = sample(Family::RootCauseChain, &mut rng);
            assert!(sampled.facts.iter().any(|f| matches!(f, RelationalFact::DependsOn { .. })));
            let ballot: Vec<&str> = std::iter::once(sampled.gold.as_str())
                .chain(sampled.distractors.iter().map(|d| d.name.as_str()))
                .collect();
            assert!(ballot.len() >= 5, "ballot {ballot:?} under 5 slots");
            let unique = ballot.iter().collect::<std::collections::BTreeSet<_>>();
            assert_eq!(unique.len(), ballot.len(), "duplicate ballot slot");
            let near = sampled
                .distractors
                .iter()
                .filter(|d| {
                    matches!(
                        d.kind,
                        DistractorKind::Symptom
                            | DistractorKind::StandaloneFailure
                            | DistractorKind::HealthyPeer
                    )
                })
                .count();
            assert!(near >= 3, "fewer than 3 near-misses: {near}");
        }
    }

    #[test]
    fn healthiest_boards_have_a_strict_winner() {
        let mut rng = Rng::new(4);
        for _ in 0..200 {
            let sampled = sample(Family::HealthiestBoard, &mut rng);
            assert!(sampled.facts.iter().any(|f| matches!(f, RelationalFact::HealthList { .. })
                || matches!(f, RelationalFact::Health { status: Health::Healthy, .. })));
            assert_eq!(sampled.distractors.len(), 4);
        }
    }

    #[test]
    fn first_restored_chains_have_a_unique_starter_shape() {
        let mut rng = Rng::new(5);
        for _ in 0..200 {
            let sampled = sample(Family::FirstRestoredChain, &mut rng);
            assert!(
                sampled.facts.iter().all(|f| matches!(f, RelationalFact::RestoresAfter { .. }))
            );
            assert!(sampled.distractors.len() >= 3);
        }
    }

    #[test]
    fn agreeing_items_carry_both_fact_kinds() {
        let mut rng = Rng::new(6);
        for _ in 0..200 {
            let sampled = sample(Family::RootCauseAgreeing, &mut rng);
            assert!(sampled.facts.iter().any(|f| matches!(f, RelationalFact::DependsOn { .. })));
            assert!(
                sampled.facts.iter().any(|f| matches!(f, RelationalFact::RestoresAfter { .. }))
            );
        }
    }

    #[test]
    fn every_sampled_item_names_are_pool_names() {
        let mut rng = Rng::new(7);
        for family in FAMILIES {
            for _ in 0..50 {
                let sampled = sample(*family, &mut rng);
                let pool = sampled.domain.names;
                assert!(pool.contains(&sampled.gold.as_str()));
                for d in &sampled.distractors {
                    assert!(pool.contains(&d.name.as_str()));
                }
            }
        }
    }

    #[test]
    fn the_score_rubric_truth_table_is_exact() {
        // Each row: (healthy, degraded, down) → level. Covers every
        // branch and the branch boundaries (exact half, strict majority,
        // tie-breaks) — the rubric stated word-for-word in SCORE_LEVELS.
        let table = [
            ((1, 0, 3), 0), // 2·3 > 4: downs are the majority
            ((0, 0, 1), 0), // 2·1 > 1: a lone down report is already critical
            ((3, 0, 1), 2), // one failure, healthy leads
            ((2, 3, 0), 2), // nothing down, degraded leads
            ((2, 0, 2), 1), // 2·2 = total is NOT a majority, but failures reach half
            ((4, 2, 0), 3), // nothing down, healthy ≥ degraded
            ((2, 2, 0), 3), // the ≥ boundary: healthy EQUALS degraded
            ((0, 3, 1), 1), // failures reach half (2·4 ≥ 4), downs not majority
            ((1, 1, 1), 1), // 2·2 ≥ 3 with one down
            ((5, 0, 1), 2), // one failure, healthy dominates
            ((1, 0, 0), 3), // single healthy report is healthy
        ];
        for ((h, d, x), expected) in table {
            assert_eq!(health_level(h, d, x), expected, "counts ({h},{d},{x})");
        }
    }

    #[test]
    fn counts_for_level_always_realizes_its_level() {
        // Property, not spot checks: for every level and every total the
        // sampler can draw, the constructed counts must land in that
        // level's band. This is the sampler invariant the level-spread
        // guarantee rests on.
        let mut rng = Rng::new(8);
        for level in 0..4 {
            for total in 1..=15 {
                // Infeasible combos the sampler never draws: level 1
                // needs a down (total ≥ 2); level 2's failure-present
                // branch needs total ≥ 4 and the sampler bumps the
                // draw to that floor.
                if level == 1 && total < 2 || level == 2 && total < 4 {
                    continue;
                }
                let (h, d, x) = counts_for_level(level, total, &mut rng);
                assert_eq!(h + d + x, total, "counts must sum to total");
                assert_eq!(health_level(h, d, x), level, "level {level} total {total}");
            }
        }
    }

    #[test]
    fn score_items_spread_across_all_four_levels() {
        let mut rng = Rng::new(9);
        let mut seen = [0usize; 4];
        for _ in 0..200 {
            let sampled = sample(Family::ScoreBoard, &mut rng);
            let (h, d, x) = count_statuses(&sampled.facts);
            // The stored gold must agree with the constructed fact set.
            assert_eq!(sampled.gold, health_level(h, d, x).to_string());
            seen[sampled.gold.parse::<usize>().unwrap()] += 1;
        }
        for (level, count) in seen.iter().enumerate() {
            assert!(*count >= 20, "level {level} drew only {count} of 200");
        }
    }

    #[test]
    fn corrupt_to_pair_flips_exactly_one_fact_and_moves_the_gold() {
        // Draw until the shape matches, then check the pair contract:
        // same length, one health fact different, gold moved to the
        // direct dependent, old gold demoted to a healthy peer.
        let mut rng = Rng::new(10);
        let mut paired = 0;
        for _ in 0..200 {
            let base = sample(Family::RootCauseChain, &mut rng);
            let Some(twin) = corrupt_to_pair(&base) else { continue };
            paired += 1;
            assert_eq!(base.facts.len(), twin.facts.len(), "one-fact flip, not a rewrite");
            let diffs: Vec<(&RelationalFact, &RelationalFact)> =
                base.facts.iter().zip(&twin.facts).filter(|(a, b)| a != b).collect();
            assert_eq!(diffs.len(), 1, "expected exactly one changed fact, got {diffs:?}");
            assert!(matches!(diffs[0].0, RelationalFact::Health { status: Health::Down, .. }));
            assert!(matches!(diffs[0].1, RelationalFact::Health { status: Health::Healthy, .. }));
            assert_ne!(base.gold, twin.gold);
            // The new gold must be the direct dependent of the old gold.
            assert!(
                base.facts.iter().any(|f| matches!(f,
                    RelationalFact::DependsOn { dependent, dependency }
                    if *dependent == twin.gold && *dependency == base.gold)),
                "twin gold is not the old gold's direct dependent"
            );
        }
        assert!(paired >= 50, "the pair shape never drew: {paired}/200");
    }

    /// The status tally reads health facts only — ordering facts
    /// (`DependsOn`, `RestoresAfter`) carry no health signal and must
    /// not be misread as report rows.
    #[test]
    fn count_statuses_skips_facts_without_health() {
        let facts = vec![
            RelationalFact::DependsOn {
                dependent: "cache-a".to_owned(),
                dependency: "db-a".to_owned(),
            },
            RelationalFact::RestoresAfter {
                later: "cache-a".to_owned(),
                earlier: "db-a".to_owned(),
            },
            RelationalFact::Health { entity: "db-a".to_owned(), status: Health::Down },
            RelationalFact::HealthList {
                entity: "cache-a".to_owned(),
                statuses: vec![Health::Degraded, Health::Healthy],
            },
        ];
        assert_eq!(count_statuses(&facts), (1, 1, 1));
    }
}
